### ISSUE TITLE
Journal Summary creates new note on execution

### ISSUE THREAD

**Issue by brokosz** [beet/alfred_noteplan_actions#11]
This is probably related to local storage, but running Journal Summary creates a new note every time. I assume this is not expected behavior? 
#10

**Comment by beet** [comment]
Ah, actually that is expected.

NotePlan's [X-Callback-Url Scheme](https://noteplan.co/faq/General/X-Callback-Url%20Scheme/) is great, but it doesn't allow for modifying the contents of existing notes, only creating new ones, or appending/prepending text to existing notes.

If we could read the contents of existing notes it might be possible to work out which journal entries need to be appended, rather than creating a new file each time.

It's a bit experimental for now, but other than duplicating the file each time, is it at all useful for you?

**Comment by brokosz** [comment]
ok, thanks Mark. yeah, I see that it could be useful for status reports, performance reviews, etc...  I was more hoping it would either do a full up replace or append since last date run.

**Comment by brokosz** [comment]
I'm digging this behavior the more I use it. no need to change it.

**Comment by beet** [comment]
Cheers, I used it at the start of the year to apply [Tim Ferris' past year review](https://tim.blog/2018/12/28/past-year-review/) and was surprised to find that I had a very long list of positive experiences, and only a few negatives, but the negatives were recurring and systemic, but also largely beyond my control.

So this year I'm taking them as an opportunity to practice amor fati :)
